name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run Linter
      run: yarn lint:check
    - name: Run Tests
      run: yarn test
    - name: 'Run Build'
      run: yarn build --noEmit
